import { format, parseISO } from "date-fns";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Scan, ScanModelInsight, ScanStatus } from "@/lib/mock-data";
import {
  extractHiveRows,
  extractRealityDefenderRows,
} from "@/lib/export-scan-report-pdf-providers";
import { formatScorePercentage } from "@/lib/percentage";

const PAGE_MARGIN = 48;
const FOOTER_RESERVE = 44;
const SECTION_GAP = 18;
const LINE_H = 12;

/** Safe basename for `${name}-report.pdf` (no path chars). */
export function safeReportFileNameBasename(title: string): string {
  const raw = (title || "scan").trim() || "scan";
  return (
    raw
      .replace(/[/\\?%*:|"<>]/g, "_")
      .replace(/\s+/g, " ")
      .replace(/^\.+|\.+$/g, "")
      .slice(0, 120)
      .trim() || "scan"
  );
}

function formatCreatedAt(iso: string): string {
  try {
    return format(parseISO(iso), "PPpp");
  } catch {
    return iso;
  }
}

function verdictLine(status: ScanStatus): string {
  switch (status) {
    case "safe":
      return "This media appears authentic based on available signals.";
    case "flagged":
      return "This media is likely AI-generated or manipulated.";
    case "suspicious":
      return "This media requires additional review.";
    case "pending":
      return "This scan is still processing.";
    case "failed":
      return "This scan did not complete successfully.";
    default:
      return "This scan is still processing.";
  }
}

function pageHeight(doc: jsPDF): number {
  return doc.internal.pageSize.getHeight();
}

function pageWidth(doc: jsPDF): number {
  return doc.internal.pageSize.getWidth();
}

function contentWidth(doc: jsPDF): number {
  return pageWidth(doc) - 2 * PAGE_MARGIN;
}

/** Ensure vertical space; add page and reset Y if needed. */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  const h = pageHeight(doc);
  if (y + needed > h - FOOTER_RESERVE) {
    doc.addPage();
    return PAGE_MARGIN + 12;
  }
  return y;
}

function drawSectionHeading(doc: jsPDF, title: string, y: number): number {
  y = ensureSpace(doc, y, 32);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(26, 32, 44);
  doc.text(title, PAGE_MARGIN, y);
  doc.setDrawColor(200, 206, 214);
  doc.setLineWidth(0.5);
  const underlineY = y + 4;
  doc.line(PAGE_MARGIN, underlineY, pageWidth(doc) - PAGE_MARGIN, underlineY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  return underlineY + 16;
}

function tableBottomMargin(): number {
  return PAGE_MARGIN + FOOTER_RESERVE;
}

function lastTableFinalY(doc: jsPDF): number {
  const last = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable;
  return last?.finalY ?? PAGE_MARGIN;
}

function addFooters(doc: jsPDF): void {
  const total = doc.getNumberOfPages();
  const w = pageWidth(doc);
  const h = pageHeight(doc);
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text("Generated by MAuthenticity", PAGE_MARGIN, h - 24);
    doc.text(`Page ${i} of ${total}`, w - PAGE_MARGIN - 72, h - 24, { align: "right" });
  }
}

function fmtNum(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(Number(n))) {
    return "—";
  }
  return String(n);
}

function modelRows(insights: ScanModelInsight[] | undefined): string[][] {
  if (!insights?.length) {
    return [["Not available", "—", "—", "—", "—", "—", "—"]];
  }
  return insights.map((m) => [
    m.name || "—",
    m.status || "—",
    m.decision || "—",
    fmtNum(m.score),
    fmtNum(m.rawScore),
    fmtNum(m.normalizedScore),
    fmtNum(m.finalScore),
  ]);
}

/**
 * Build and download a client-ready PDF report for the current scan (no backend).
 */
export async function exportScanReportPdf(scan: Scan): Promise<void> {
  const doc = new jsPDF({ unit: "pt", format: "letter", compress: true });
  const cw = contentWidth(doc);
  let y = PAGE_MARGIN;

  // —— A. Header ——
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text("MAuthenticity", PAGE_MARGIN, y);
  y += 28;

  doc.setFontSize(15);
  doc.text("Scan Report", PAGE_MARGIN, y);
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const genAt = format(new Date(), "PPpp");
  const headerLines = doc.splitTextToSize(
    `File: ${scan.title}\nGenerated: ${genAt}\nScan ID: ${scan.id}`,
    cw,
  );
  y = ensureSpace(doc, y, headerLines.length * LINE_H + 8);
  doc.text(headerLines, PAGE_MARGIN, y);
  y += headerLines.length * LINE_H + SECTION_GAP;

  // —— B. Summary ——
  y = drawSectionHeading(doc, "Summary", y);
  const summaryBody: string[][] = [
    ["Status", scan.status],
    ["Confidence", `${scan.confidence}%`],
    ["Source", scan.source === "url" ? "URL" : "Upload"],
    ["Media kind", scan.kind],
    ["Created", formatCreatedAt(scan.createdAt)],
    // ["Provider request ID", scan.providerRequestId?.trim() || "Not available"],
  ];
  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: summaryBody,
    theme: "plain",
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
    styles: {
      fontSize: 9,
      cellPadding: 5,
      textColor: [55, 65, 81],
      lineColor: [226, 232, 240],
      lineWidth: 0.25,
    },
    headStyles: {
      fillColor: [241, 245, 249],
      textColor: [30, 41, 59],
      fontStyle: "bold",
      fontSize: 9,
    },
    columnStyles: { 0: { cellWidth: cw * 0.32 }, 1: { cellWidth: cw * 0.68 } },
  });
  y = lastTableFinalY(doc) + SECTION_GAP;

  // —— C. Key findings ——
  y = drawSectionHeading(doc, "Key findings", y);
  const signalCount =
    typeof scan.modelCount === "number" && scan.modelCount >= 0
      ? scan.modelCount
      : (scan.modelInsights?.length ?? scan.detections?.length ?? 0);
  const findings = `${verdictLine(scan.status)}\n\nSignals / models: ${signalCount}`;
  const findLines = doc.splitTextToSize(findings, cw);
  y = ensureSpace(doc, y, findLines.length * LINE_H + 8);
  doc.text(findLines, PAGE_MARGIN, y);
  y += findLines.length * LINE_H + SECTION_GAP;

  // —— D. Signal scores ——
  y = drawSectionHeading(doc, "Signal scores", y);
  const detRows: string[][] =
    scan.detections?.length > 0
      ? scan.detections.map((d) => [d.label, `${formatScorePercentage(d.score)}%`])
      : [["Not available", "—"]];
  autoTable(doc, {
    startY: y,
    head: [["Label", "Score"]],
    body: detRows,
    theme: "striped",
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
    styles: { fontSize: 9, cellPadding: 5, textColor: [55, 65, 81] },
    headStyles: { fillColor: [30, 41, 59], textColor: [248, 250, 252], fontStyle: "bold" },
    columnStyles: { 0: { cellWidth: cw * 0.62 }, 1: { cellWidth: cw * 0.38, halign: "right" } },
  });
  y = lastTableFinalY(doc) + SECTION_GAP;

  // —— E. Metadata ——
  y = drawSectionHeading(doc, "Metadata", y);
  const metaRows =
    scan.metadata?.length > 0
      ? scan.metadata.map((m) => [m.key, m.value])
      : [["Not available", "—"]];
  autoTable(doc, {
    startY: y,
    head: [["Property", "Value"]],
    body: metaRows,
    theme: "plain",
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
    styles: {
      fontSize: 8,
      cellPadding: 4,
      textColor: [55, 65, 81],
      overflow: "linebreak",
      cellWidth: "wrap",
    },
    headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: "bold" },
    columnStyles: { 0: { cellWidth: cw * 0.28 }, 1: { cellWidth: cw * 0.72 } },
  });
  y = lastTableFinalY(doc) + SECTION_GAP;

  // —— F. Model insights ——
  y = drawSectionHeading(doc, "Model insights", y);
  autoTable(doc, {
    startY: y,
    head: [["Name", "Status", "Decision", "Score", "Raw", "Norm.", "Final"]],
    body: modelRows(scan.modelInsights),
    theme: "striped",
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
    styles: { fontSize: 7, cellPadding: 3, textColor: [55, 65, 81], overflow: "linebreak" },
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [248, 250, 252],
      fontStyle: "bold",
      fontSize: 7,
    },
    columnStyles: {
      0: { cellWidth: cw * 0.2 },
      1: { cellWidth: cw * 0.14 },
      2: { cellWidth: cw * 0.18 },
      3: { cellWidth: cw * 0.12 },
      4: { cellWidth: cw * 0.12 },
      5: { cellWidth: cw * 0.12 },
      6: { cellWidth: cw * 0.12 },
    },
  });
  y = lastTableFinalY(doc) + SECTION_GAP;

  // —— F2. Hive Results (provider-specific; only if rows exist) ——
  const hiveRows = extractHiveRows(scan);
  if (hiveRows.length > 0) {
    y = drawSectionHeading(doc, "Hive Results", y);
    autoTable(doc, {
      startY: y,
      head: [["Field", "Value"]],
      body: hiveRows,
      theme: "plain",
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
      styles: {
        fontSize: 8,
        cellPadding: 4,
        textColor: [55, 65, 81],
        overflow: "linebreak",
        cellWidth: "wrap",
      },
      headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: "bold" },
      columnStyles: { 0: { cellWidth: cw * 0.28 }, 1: { cellWidth: cw * 0.72 } },
    });
    y = lastTableFinalY(doc) + SECTION_GAP;
  }

  // —— F3. Reality Defender Results (provider-specific; only if rows exist) ——
  const rdRows = extractRealityDefenderRows(scan);
  if (rdRows.length > 0) {
    y = drawSectionHeading(doc, "Reality Defender Results", y);
    autoTable(doc, {
      startY: y,
      head: [["Field", "Value"]],
      body: rdRows,
      theme: "plain",
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
      styles: {
        fontSize: 8,
        cellPadding: 4,
        textColor: [55, 65, 81],
        overflow: "linebreak",
        cellWidth: "wrap",
      },
      headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: "bold" },
      columnStyles: { 0: { cellWidth: cw * 0.28 }, 1: { cellWidth: cw * 0.72 } },
    });
    y = lastTableFinalY(doc) + SECTION_GAP;
  }

  // —— G. Timeline ——
  y = drawSectionHeading(doc, "Timeline", y);
  const tlRows =
    scan.timeline?.length > 0
      ? scan.timeline.map((t) => [t.time, t.event])
      : [["—", "Not available"]];
  autoTable(doc, {
    startY: y,
    head: [["Time", "Event"]],
    body: tlRows,
    theme: "plain",
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN, bottom: tableBottomMargin() },
    styles: { fontSize: 8, cellPadding: 4, textColor: [55, 65, 81], overflow: "linebreak" },
    headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: "bold" },
    columnStyles: { 0: { cellWidth: cw * 0.18 }, 1: { cellWidth: cw * 0.82 } },
  });
  y = lastTableFinalY(doc) + SECTION_GAP;

  // —— Optional: heatmaps note ——
  const hasHeatmaps = (scan.heatmaps?.length ?? 0) > 0;
  if (hasHeatmaps || scan.heatmapsExpired) {
    y = drawSectionHeading(doc, "Heatmaps", y);
    const note = hasHeatmaps
      ? "Heatmap previews are available in the app view. Images are not embedded in this export for reliability and access control."
      : "Heatmap previews were not included in this export. Open the scan in the app to view details.";
    const noteLines = doc.splitTextToSize(note, cw);
    y = ensureSpace(doc, y, noteLines.length * LINE_H + 8);
    doc.text(noteLines, PAGE_MARGIN, y);
    y += noteLines.length * LINE_H + SECTION_GAP;
  }

  addFooters(doc);

  const filename = `${safeReportFileNameBasename(scan.title)}-report.pdf`;
  doc.save(filename);
}
